name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: action/setup-python@v4
      with:
      python-version: 3.9
    - name: Install dependencies
      run pip install -r requrements.txt || echo "No dependencies"
    - name: Run script
      run: python main.py
