name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt || echo "No dependencies"
    - name: Run script
      run: python main.py
    - name: Install dependencies
      run: pip install pytest
    - name: Run tests
      run: pytest -v
    - name: Clean pycache
      run:
        find . -type d -name "__pycache__" -exec rm -r {} +

